### ISSUE TITLE
Support for Columns

### ISSUE THREAD

**Issue by 2Belette** [andresth/Kandroid#20] opened 2017-04-24 20:16 UTC
would be great to have a way to support column / having view by column

**Comment by TomFernandes** [comment] 2018-06-30 07:11
I can second that and I am irritated, that kandroid does not support columns. For me - personally - having and using columns (e.g. backlog/ready/in progress) is the whole point of using a kanban system over any other kind of todo list software. For me - and I also think for a lot of other people - it's a key feature feature to have tasks organized by columns and displaying the progress or changing the progress by just moving it from one column to the next.

**Comment by nekohayo** [comment] 2019-06-14 14:16
As a user, I will ask a rethorical question here: while everybody agrees that columns are usually part of kanban boards, how do you even imagine this fitting on a phone screen? Held vertically, it barely can fit the information of a single column...

On the other hand, looking more closely at the app's UI today, I realized that there is some support for columns besides the fact that you can edit each task's properties including columns: if you exit the "Dashboard" UI mode by going into the sidebar/hamburger menu, and instead enter one of your specific boards/projects, then you can see that the columns are represented at the top; start by swiping from right to left to get to the first column that is on the "right" of the screen, and then you can continue swiping right and left to move across columns. That same UI even supports swimlanes, actually (so issue #19 is moot).

So unless you're looking for something drastically different than what the app author implemented so far, I guess this could be considered a "it already works" scenario.

**Comment by ghost** [comment] 2021-03-29 15:42
I think part of the problem is that by default, the main screen shows all projects, and just "expands" them out to show the various tasks when you tap on them.  Since there is no way to navigate columns from the main display, it leads people to believe they cannot go from one column to the next.

Instead, it might help to cause the app to go into that project when it's tapped, instead of simply expanding, and requiring the person to go into the main menu and select the project from there to actually view the full, navigable project.

Inside the project, it would also be useful to include a shortcut to move tasks from one column to another, such as buttons to the left and right that moves the task accordingly, or a long-press menu that offers the options.  It is a bit of a hassle to have to go into the task details, the task menu, the column options page, and then choose the column, just for the sake of marking a task done.

Another possible shortcut would be to make the tasks draggable after a long press; in this way, you can move them between swimlanes, or, by holding the task against the left or right of the display, you can trigger the app to move to the next column where the task can be put back down.

I hope this helps!

**Closed** 2024-07-25 09:29 UTC
