### ISSUE TITLE
Subtasks and comments in blank

### ISSUE THREAD

**Issue by EstebanMonge** [andresth/Kandroid#1] opened 2017-02-03 18:09 UTC
Hello, great job!

Subtasks and Comments are displayed with white font.

**Comment by andresth** [comment] 2017-02-03 20:14
Thanks.

Can you give me more details on your configuration, like device manufacturer, Android version/Mod, Theme?
Because on my development devices its black font on white background.

**Comment by EstebanMonge** [comment] 2017-02-03 20:31
Hello:

We have installed in one Huawei Mate 8 with EMUI 4.0.

![index](https://cloud.githubusercontent.com/assets/1070783/22607394/503d18d8-ea1d-11e6-88b2-f8a0dd16dd62.jpeg)
![index2](https://cloud.githubusercontent.com/assets/1070783/22607395/503ea824-ea1d-11e6-9421-c5e92e87fca9.jpeg)


Also we have installed in one Samsung S7.

**Comment by EstebanMonge** [comment] 2017-02-03 20:34
The theme is Spectrum, I change it with other that the phone has preinstalled but the font still white.

**Comment by andresth** [comment] 2017-02-03 21:38
I was able to reproduce it using emulators running Android 5 and 6.
Now it's now fixed.

**Closed by andresth** 2017-02-03 21:38 UTC
Labels: bug
